django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('poll/', include('poll.urls')),
    path('admin/', admin.site.urls),
]

poll/urls.py
from django.urls import path

from . import views

app_name = 'poll'      # Namespaces added to URLconf.
urlpatterns = [
    # /poll/
    path('', views.index, name='index'),
    # /poll/<question_id>/ (example: /poll/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # /poll/<question_id>/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # /poll/<question_id>/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

poll/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

poll/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'poll/index.html', context)


def detail(request, question_id):
    """
    from django.http import Http404

    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    """
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'poll/detail.html',
                      {'question': question, 'error_message':
                          "You didn't select a choice",
                       })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpRespononseRedirect after successfully
        # dealing with POST data.  This prevents data from being posted
        # twice if a user hits the Back button.
        return HttpResponseRedirect(reverse('poll:results',
                                            args=(question.id,)))

poll/templates/poll/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Questions</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

{% if error_message %} <p><strong>{{ error_message }}</strong>
</p>{% endif %}

<form action="{% url 'poll:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice"
               id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
        <label for="choice{{ forloop.counter }}">
            {{ choice.choice_text }}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>
</body>
</html>

poll/templates/poll/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <!--<li><a href="/poll/{/{ question.id }}/">{/{ question.question_text }}</a></li>
            ...
            <li><a href="{/% url 'detail' question.id %}">{/{ question.question_text }}</a></li>-->

            <!--Added namespaces-->
            <li><a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a></li>

            <!-- the 'name' value as called by the {/% url %} template tag:
                path('<int:question_id>/', views.detail, name='detail') -->
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

poll/templates/poll/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ question.question_text }}: Results</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }}
        vote{{ choice.votes|pluralize }}</li>
        <!--pluralize возвращает суффикс, если значение не равно 1.
        По умолчанию этот суффикс равен 's'.-->
    {% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id %}">Do you wanna vote again?</a>
</body>
</html>

poll/templates/poll/some.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>JS learning</title>
</head>
<body>
<script>
    let firstNum = 12;
    let secondNum = 34;
    document.write ("Результат: " + firstNum + secondNum);  // сложатся как строки;
    document.write ("<br>" + Math.PI + "<br>");  // можно использовать теги внутри кода;
    document.writeln ("Результ сложения: ", firstNum + secondNum);  // сложатся как числа;

    let bool = false;
    if (!bool) {    // быстрое отрицание вне сложныъ логических операций;
        console.log (bool + " is false");
    }

    let colors = Array ("Red", "Green","Blue");
    colors.push ("Grey");  // добавление элемента в конец массива;
    document.write ("<br>" + colors);

    let res = 3;
    switch (res) {      // повторение конструкции 'switch-case-case'
        case 1:
            alert ("Res is 1");
            break;
        case 2:
            alert ("Res is 2");
            break;
        case 3:
            alert ("Res is 3");
            break;
        default:
            alert ("Res is not defined for me");
            break;
    }

    let person = {                          // создание объекта - словарь по сути;
        firstName: "Sergio",
        age: 27,
        children: ['Angelina', 'Jessica'],
        adress: {
            state: 'Omsk region',
            city: 'Omsk',
            street: 'Young Guardion st.'
        },
        NameAge: function () {
            return this.firstName + ", age is - " + this.age;
        }
    };
    document.write ('<br>' + person.NameAge ());

    let apple = Object ();      // ещё вариант создания объекта;
    apple.color = 'green';
    apple.shape = 'round';
    document.write ('<br>' + apple.color);

    function Fruit (color, shape) {
        this.color = color;
        this.shape = shape;
    }
    let melon = new Fruit ('yellow', 'round');
    document.write ('<br>' + melon.color);
</script>
</body>
</html>

poll/templates/poll/some2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>JS learning 2</title>
</head>
<body>
<p id="text">Some so important text</p>
<button onmouseover="changeColor('red');">Unblue this text</button>     <!--свойство по наведению мыши на объект-->
<button onclick="changeColor('blue');">Text is FUCKING BLUE!</button>   <!--свойство по нажатию на кнопку-->
<br>
<script>
    /* Функция для кнопочек - комментарий большим сделан ради тренировки */
    function changeColor (newColor='white') {
        let element = document.getElementById("text");                  // локальное пространство имён;
        element.style.color = newColor;
    }
</script>
<br>
<form name="mySimpleForm" action="" onsubmit="return validateForm()" method="post">  <!--простенькая формочка-->
    <label>Name: <input type="text" name="fname"></label>
    <label>Phone: <input type="number" name="ftel"></label>
    <input type="submit" value="Submit">
</form>
<script>
    function validateForm () {
        let element = document.forms["mySimpleForm"]["fname"].value;    // локальное пространство имён;
        let tel = document.forms["mySimpleForm"]["ftel"].value;
        if (element === "") {
            alert ("Just input your fucking name already!");            // если форма не заполнена;
            return false;           // отдавать ' false ' чтобы страничка не перезагружалась;
        } else if (tel === "") {
            alert ("Give me your number!");
            return false;
        }
    }
</script>
</body>
</html>